# Generated by Django 4.2 on 2023-10-22 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_intro_user_mobile_user_proflie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='proflie',
            new_name='profile',
        ),
    ]
