# Generated by Django 4.2 on 2023-10-24 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_posttag_post_remove_posttag_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catgories',
            new_name='categories',
        ),
    ]
