# Generated by Django 4.2 on 2023-10-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_rename_catgories_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imgae',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
